{% set version = "0.0.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ips
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ips_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ips/ips_{{ version }}.tar.gz
  sha256: 1cb2de135ba9927cc1984aa323300d0df2b64f37f0928df57cea6f922a55da6e

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-xml
    - r-ape
    - r-data.table
    - r-phangorn
    - r-plyr
  run:
    - r-base
    - r-xml
    - r-ape
    - r-data.table
    - r-phangorn
    - r-plyr

test:
  commands:
    - $R -e "library('ips')"           # [not win]
    - "\"%R%\" -e \"library('ips')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ips
  license: GPL-3.0-only
  summary: Functions that wrap popular phylogenetic software for sequence alignment, masking of sequence alignments, and estimation of phylogenies and ancestral character states.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: ips
# Version: 0.0.11
# Date: 2019-06-20
# Title: Interfaces to Phylogenetic Software in R
# Authors@R: c( person("Christoph", "Heibl", email = "christoph.heibl@gmx.net", role = c("aut", "cre")), person("Natalie", "Cusimano", role = c("aut")), person("Franz-Sebastian", "Krah", role = c("aut")))
# Depends: R (>= 3.2.0), ape
# Imports: phangorn, plyr, seqinr, XML
# Description: Functions that wrap popular phylogenetic software for sequence alignment, masking of sequence alignments, and estimation of phylogenies and ancestral character states.
# License: GPL-3
# Encoding: UTF-8
# NeedsCompilation: no
# Repository: CRAN
# RoxygenNote: 6.1.1
# Packaged: 2019-07-04 15:51:55 UTC; heibl
# Author: Christoph Heibl [aut, cre], Natalie Cusimano [aut], Franz-Sebastian Krah [aut]
# Maintainer: Christoph Heibl <christoph.heibl@gmx.net>
# Date/Publication: 2019-07-04 16:30:03 UTC
